[workspace]

members = [
    "day_01",
    "day_02",
    "day_03",
    "day_04",
    "day_05",
    "day_06",
    "day_07",
    "day_08",
    "day_09",
    "day_10",
    "day_11",
    "day_12",
]

[workspace.dependencies]
nom = "7.1.1"
array_tool = "1.0.3"
itertools = "0.10.5"
pathfinding = "4.0.0"
